server:
  port: 8081
#spring:
#  dubbo:
#    application:
#      name: service-provider
#    base-package: cn.txs.dubboprovider # dubbo服务发布者所在的包
#    registry:
#      address: 172.171.51.151 # zookeeper注册中心的地址
#      port: 2181       # zookeeper注册中心的端口
#      protocol: zookeeper
#      register: true
#    protocol:
#      name: dubbo
#      port: 20880
#      accesslog: true
#    provider:
#      retries: 1
#      delay: -1