server:
  port: 8082
#spring:
#  dubbo:
#    application:
#      name: service-consumer
#    base-package: cn.txs.dubboprovider  # dubbo服务调用者所在的包
#    registry:
#      address: 172.171.51.151  # zookeeper注册中心的地址
#      port: 2181              # zookeeper注册中心的端口
#      protocol: zookeeper
#      subscribe: true
#    protocol:
#      name: dubbo
#      host: 172.171.51.151
#    consumer:
#      timeout: 1000
#      check: false  # 服务启动时检查被调用服务是否可用
#      retries: 2    # 服务调用重试次数